<a href="https://colab.research.google.com/github/RAGHAVJINDGER/Exploratory-Data-Analysis/blob/main/Experiment2_28-07-26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = np.arange(15, 30).reshape(5, 3)

dfx = pd.DataFrame(
    data,
    index=['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard'],
    columns=['Amazon', 'Flipkart', 'Croma']
)

dfx

          Amazon  Flipkart  Croma
Laptop        15        16     17
Phone         18        19     20
Tablet        21        22     23
Monitor       24        25     26
Keyboard      27        28     29

In [3]:
dfx['RelianceDigital'] = np.nan

dfx.loc['Mouse'] = np.arange(15, 19)

dfx.loc['Printer'] = np.nan

dfx['Myntra'] = np.nan

dfx['RelianceDigital']['Laptop'] = 20.

dfx

/tmp/ipykernel_1077/3734262546.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfx['RelianceDigital']['Laptop'] = 20.

          Amazon  Flipkart  Croma  RelianceDigital  Myntra
Laptop      15.0      16.0   17.0             20.0     NaN
Phone       18.0      19.0   20.0              NaN     NaN
Tablet      21.0      22.0   23.0              NaN     NaN
Monitor     24.0      25.0   26.0              NaN     NaN
Keyboard    27.0      28.0   29.0              NaN     NaN
Mouse       15.0      16.0   17.0             18.0     NaN
Printer      NaN       NaN    NaN              NaN     NaN

In [4]:
# Check missing values

dfx.isnull()

          Amazon  Flipkart  Croma  RelianceDigital  Myntra
Laptop     False     False  False            False    True
Phone      False     False  False             True    True
Tablet     False     False  False             True    True
Monitor    False     False  False             True    True
Keyboard   False     False  False             True    True
Mouse      False     False  False            False    True
Printer     True      True   True             True    True

In [5]:
# Check non-missing values

dfx.notnull()

          Amazon  Flipkart  Croma  RelianceDigital  Myntra
Laptop      True      True   True             True   False
Phone       True      True   True            False   False
Tablet      True      True   True            False   False
Monitor     True      True   True            False   False
Keyboard    True      True   True            False   False
Mouse       True      True   True             True   False
Printer    False     False  False            False   False

In [6]:
# Count missing values in each column

dfx.isnull().sum()

Amazon             1
Flipkart           1
Croma              1
RelianceDigital    5
Myntra             7
dtype: int64

In [7]:
# Count total missing values

dfx.isnull().sum().sum()

np.int64(15)

In [8]:
# Count reported/non-missing values

dfx.count()

Amazon             6
Flipkart           6
Croma              6
RelianceDigital    2
Myntra             0
dtype: int64

In [9]:
# Display only non-missing values

dfx.RelianceDigital[dfx.RelianceDigital.notnull()]

Laptop    20.0
Mouse     18.0
Name: RelianceDigital, dtype: float64

In [10]:
# Drop missing values from one column

dfx.RelianceDigital.dropna()

Laptop    20.0
Mouse     18.0
Name: RelianceDigital, dtype: float64

In [11]:
# Drop rows containing NaN

dfx.dropna()

Empty DataFrame
Columns: [Amazon, Flipkart, Croma, RelianceDigital, Myntra]
Index: []

In [12]:
# Drop rows only if all values are NaN

dfx.dropna(how='all')

          Amazon  Flipkart  Croma  RelianceDigital  Myntra
Laptop      15.0      16.0   17.0             20.0     NaN
Phone       18.0      19.0   20.0              NaN     NaN
Tablet      21.0      22.0   23.0              NaN     NaN
Monitor     24.0      25.0   26.0              NaN     NaN
Keyboard    27.0      28.0   29.0              NaN     NaN
Mouse       15.0      16.0   17.0             18.0     NaN

In [13]:
# Drop columns only if all values are NaN

dfx.dropna(how='all', axis=1)

          Amazon  Flipkart  Croma  RelianceDigital
Laptop      15.0      16.0   17.0             20.0
Phone       18.0      19.0   20.0              NaN
Tablet      21.0      22.0   23.0              NaN
Monitor     24.0      25.0   26.0              NaN
Keyboard    27.0      28.0   29.0              NaN
Mouse       15.0      16.0   17.0             18.0
Printer      NaN       NaN    NaN              NaN

In [14]:
# Keep columns having at least 5 non-missing values

dfx.dropna(thresh=5, axis=1)

          Amazon  Flipkart  Croma
Laptop      15.0      16.0   17.0
Phone       18.0      19.0   20.0
Tablet      21.0      22.0   23.0
Monitor     24.0      25.0   26.0
Keyboard    27.0      28.0   29.0
Mouse       15.0      16.0   17.0
Printer      NaN       NaN    NaN

In [15]:
# Mathematical operations with NaN

ar1 = np.array([100, 200, np.nan, 300])

ser1 = pd.Series(ar1)

ar1.mean(), ser1.mean()

(np.float64(nan), np.float64(200.0))

In [16]:
# Sum

ser2 = dfx.RelianceDigital

ser2.sum()

np.float64(38.0)

In [17]:
# Average

ser2.mean()
# Cumulative sum

ser2.cumsum()

Laptop      20.0
Phone        NaN
Tablet       NaN
Monitor      NaN
Keyboard     NaN
Mouse       38.0
Printer      NaN
Name: RelianceDigital, dtype: float64

In [18]:
# Fill NaN with 0

filledDf = dfx.fillna(0)

filledDf

          Amazon  Flipkart  Croma  RelianceDigital  Myntra
Laptop      15.0      16.0   17.0             20.0     0.0
Phone       18.0      19.0   20.0              0.0     0.0
Tablet      21.0      22.0   23.0              0.0     0.0
Monitor     24.0      25.0   26.0              0.0     0.0
Keyboard    27.0      28.0   29.0              0.0     0.0
Mouse       15.0      16.0   17.0             18.0     0.0
Printer      0.0       0.0    0.0              0.0     0.0

In [19]:
dfx.mean()
filledDf.mean()

Amazon             17.142857
Flipkart           18.000000
Croma              18.857143
RelianceDigital     5.428571
Myntra              0.000000
dtype: float64

In [20]:
filledDf.mean()

Amazon             17.142857
Flipkart           18.000000
Croma              18.857143
RelianceDigital     5.428571
Myntra              0.000000
dtype: float64

In [21]:
# Forward filling

dfx.RelianceDigital.ffill()

Laptop      20.0
Phone       20.0
Tablet      20.0
Monitor     20.0
Keyboard    20.0
Mouse       18.0
Printer     18.0
Name: RelianceDigital, dtype: float64

In [22]:
# Backward filling

dfx.RelianceDigital.bfill()

Laptop      20.0
Phone       18.0
Tablet      18.0
Monitor     18.0
Keyboard    18.0
Mouse       18.0
Printer      NaN
Name: RelianceDigital, dtype: float64

In [23]:
#Imputation techniques

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer

In [24]:
# Create sample DataFrame with missing values

df = pd.DataFrame({
    "Area": [1200, np.nan, 1500, 1800, 1000],
    "Price": [5000000, 6000000, np.nan, 8000000, 4500000],
    "Type": ["Flat", "Villa", "Flat", np.nan, "Villa"]
})

df

     Area      Price   Type
0  1200.0  5000000.0   Flat
1     NaN  6000000.0  Villa
2  1500.0        NaN   Flat
3  1800.0  8000000.0    NaN
4  1000.0  4500000.0  Villa

In [25]:
# 1. Mean Imputation (Numerical)

mean_imputer = SimpleImputer(strategy="mean")

df["Area_Mean"] = mean_imputer.fit_transform(
    df[["Area"]]
)

df

     Area      Price   Type  Area_Mean
0  1200.0  5000000.0   Flat     1200.0
1     NaN  6000000.0  Villa     1375.0
2  1500.0        NaN   Flat     1500.0
3  1800.0  8000000.0    NaN     1800.0
4  1000.0  4500000.0  Villa     1000.0

In [26]:
# 2. Median Imputation
# Numerical - robust to outliers

median_imputer = SimpleImputer(strategy="median")

df["Price_Median"] = median_imputer.fit_transform(
    df[["Price"]]
)

df

     Area      Price   Type  Area_Mean  Price_Median
0  1200.0  5000000.0   Flat     1200.0     5000000.0
1     NaN  6000000.0  Villa     1375.0     6000000.0
2  1500.0        NaN   Flat     1500.0     5500000.0
3  1800.0  8000000.0    NaN     1800.0     8000000.0
4  1000.0  4500000.0  Villa     1000.0     4500000.0

In [28]:
# 3. Mode Imputation
# Categorical - most frequent

mode_imputer = SimpleImputer(strategy="most_frequent")

df["Type_Mode"] = mode_imputer.fit_transform(
    df[["Type"]]
).ravel()

df

     Area      Price   Type  Area_Mean  Price_Median Type_Mode
0  1200.0  5000000.0   Flat     1200.0     5000000.0      Flat
1     NaN  6000000.0  Villa     1375.0     6000000.0     Villa
2  1500.0        NaN   Flat     1500.0     5500000.0      Flat
3  1800.0  8000000.0    NaN     1800.0     8000000.0      Flat
4  1000.0  4500000.0  Villa     1000.0     4500000.0     Villa

In [29]:
# 4. MICE Imputation
# Multivariate Imputation by Chained Equations

num_cols = ["Area", "Price"]

mice_imputer = IterativeImputer(
    max_iter=10,
    random_state=42
)

df_mice = df[num_cols].copy()

df_mice.iloc[:, :] = mice_imputer.fit_transform(df_mice)

df["Area_MICE"] = df_mice["Area"]

df["Price_MICE"] = df_mice["Price"]

print(df)

     Area      Price   Type  Area_Mean  Price_Median Type_Mode    Area_MICE  \
0  1200.0  5000000.0   Flat     1200.0     5000000.0      Flat  1200.000000
1     NaN  6000000.0  Villa     1375.0     6000000.0     Villa  1409.246587
2  1500.0        NaN   Flat     1500.0     5500000.0      Flat  1500.000000
3  1800.0  8000000.0    NaN     1800.0     8000000.0      Flat  1800.000000
4  1000.0  4500000.0  Villa     1000.0     4500000.0     Villa  1000.000000

     Price_MICE
0  5.000000e+06
1  6.000000e+06
2  5.875000e+06
3  8.000000e+06
4  4.500000e+06