<a href="https://colab.research.google.com/github/RAGHAVJINDGER/Exploratory-Data-Analysis/blob/main/Experiment3_04-08-26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

uploaded = files.upload()

Saving CreditCard.zip to CreditCard.zip

In [3]:
import zipfile
import os

In [5]:
import zipfile
import os

zip_file = "CreditCard.zip"

extract_path = "/content/fraud_data"

with zipfile.ZipFile(zip_file, "r") as z:
    z.extractall(extract_path)

print(os.listdir(extract_path))

['CreditCard']

In [6]:
import os

print(os.listdir('/content/fraud_data/CreditCard'))

['fraudTest.csv', 'fraudTrain.csv']

In [7]:
import pandas as pd

columns = [
    'amt',
    'city_pop',
    'lat',
    'long',
    'merch_lat',
    'merch_long',
    'is_fraud'
]

train_df = pd.read_csv(
    '/content/fraud_data/CreditCard/fraudTrain.csv',
    usecols=columns
)

test_df = pd.read_csv(
    '/content/fraud_data/CreditCard/fraudTest.csv',
    usecols=columns
)

print("Training Dataset Shape:", train_df.shape)
print("Testing Dataset Shape:", test_df.shape)

train_df.head()

Training Dataset Shape: (1296675, 7)
Testing Dataset Shape: (555719, 7)

      amt      lat      long  city_pop  merch_lat  merch_long  is_fraud
0    4.97  36.0788  -81.1781      3495  36.011293  -82.048315         0
1  107.23  48.8878 -118.2105       149  49.159047 -118.186462         0
2  220.11  42.1808 -112.2620      4154  43.150704 -112.154481         0
3   45.00  46.2306 -112.1138      1939  47.034331 -112.561071         0
4   41.96  38.4207  -79.4629        99  38.674999  -78.632459         0

In [8]:
# Exp. 5.1 - Discretization and Binning

amount = train_df['amt']

amount.head(10)

0      4.97
1    107.23
2    220.11
3     45.00
4     41.96
5     94.63
6     44.54
7     71.65
8      4.27
9    198.39
Name: amt, dtype: float64

In [9]:
bins = [0, 50, 100, 500, 1000, float('inf')]

category = pd.cut(
    amount,
    bins=bins,
    include_lowest=True
)

category

0          (-0.001, 50.0]
1          (100.0, 500.0]
2          (100.0, 500.0]
3          (-0.001, 50.0]
4          (-0.001, 50.0]
                ...
1296670    (-0.001, 50.0]
1296671     (50.0, 100.0]
1296672    (100.0, 500.0]
1296673     (50.0, 100.0]
1296674    (-0.001, 50.0]
Name: amt, Length: 1296675, dtype: category
Categories (5, interval[float64, right]): [(-0.001, 50.0] < (50.0, 100.0] < (100.0, 500.0] <
                                           (500.0, 1000.0] < (1000.0, inf]]

In [10]:
pd.Series(category).value_counts().sort_index()

amt
(-0.001, 50.0]     672299
(50.0, 100.0]      389483
(100.0, 500.0]     219262
(500.0, 1000.0]     11695
(1000.0, inf]        3936
Name: count, dtype: int64

In [11]:
bin_names = [
    'Very Low',
    'Low',
    'Medium',
    'High',
    'Very High'
]

amount_category = pd.cut(
    amount,
    bins=bins,
    labels=bin_names,
    include_lowest=True
)

amount_category

0          Very Low
1            Medium
2            Medium
3          Very Low
4          Very Low
             ...
1296670    Very Low
1296671         Low
1296672      Medium
1296673         Low
1296674    Very Low
Name: amt, Length: 1296675, dtype: category
Categories (5, object): ['Very Low' < 'Low' < 'Medium' < 'High' < 'Very High']

In [12]:
pd.Series(amount_category).value_counts()

amt
Very Low     672299
Low          389483
Medium       219262
High          11695
Very High      3936
Name: count, dtype: int64

In [13]:
pd.cut(
    amount,
    5,
    precision=2
)

0          (-27.95, 5790.58]
1          (-27.95, 5790.58]
2          (-27.95, 5790.58]
3          (-27.95, 5790.58]
4          (-27.95, 5790.58]
                 ...
1296670    (-27.95, 5790.58]
1296671    (-27.95, 5790.58]
1296672    (-27.95, 5790.58]
1296673    (-27.95, 5790.58]
1296674    (-27.95, 5790.58]
Name: amt, Length: 1296675, dtype: category
Categories (5, interval[float64, right]): [(-27.95, 5790.58] < (5790.58, 11580.16] <
                                           (11580.16, 17369.74] < (17369.74, 23159.32] <
                                           (23159.32, 28948.9]]

In [14]:
equal_bins = pd.cut(
    amount,
    5,
    precision=2
)

pd.Series(equal_bins).value_counts().sort_index()

amt
(-27.95, 5790.58]       1296572
(5790.58, 11580.16]          77
(11580.16, 17369.74]         20
(17369.74, 23159.32]          1
(23159.32, 28948.9]           5
Name: count, dtype: int64

In [15]:
randomNumbers = train_df['amt'].sample(
    n=2000,
    random_state=42
)

category3 = pd.qcut(
    randomNumbers,
    4
)

category3

1045211             (81.958, 4430.83]
547406               (47.615, 81.958]
110142     (1.0090000000000001, 9.68]
1285953    (1.0090000000000001, 9.68]
271705               (47.615, 81.958]
                      ...
183823               (47.615, 81.958]
600757              (81.958, 4430.83]
387209                 (9.68, 47.615]
779821              (81.958, 4430.83]
811733               (47.615, 81.958]
Name: amt, Length: 2000, dtype: category
Categories (4, interval[float64, right]): [(1.0090000000000001, 9.68] < (9.68, 47.615] < (47.615, 81.958] <
                                           (81.958, 4430.83]]

In [16]:
pd.Series(category3).value_counts().sort_index()

amt
(1.0090000000000001, 9.68]    500
(9.68, 47.615]                500
(47.615, 81.958]              500
(81.958, 4430.83]             500
Name: count, dtype: int64

In [17]:
quartile_names = [
    'Q1 - Very Low',
    'Q2 - Low',
    'Q3 - High',
    'Q4 - Very High'
]

amount_quartile = pd.qcut(
    randomNumbers,
    4,
    labels=quartile_names
)

amount_quartile

1045211    Q4 - Very High
547406          Q3 - High
110142      Q1 - Very Low
1285953     Q1 - Very Low
271705          Q3 - High
                ...
183823          Q3 - High
600757     Q4 - Very High
387209           Q2 - Low
779821     Q4 - Very High
811733          Q3 - High
Name: amt, Length: 2000, dtype: category
Categories (4, object): ['Q1 - Very Low' < 'Q2 - Low' < 'Q3 - High' < 'Q4 - Very High']

In [18]:
pd.Series(amount_quartile).value_counts()

amt
Q1 - Very Low     500
Q2 - Low          500
Q3 - High         500
Q4 - Very High    500
Name: count, dtype: int64

In [19]:
# Exp. 5.2 - Feature Scaling and Normalization

features = [
    'amt',
    'city_pop',
    'lat',
    'long',
    'merch_lat',
    'merch_long'
]

df_scaling = train_df[features].copy()

df_scaling.head()

      amt  city_pop      lat      long  merch_lat  merch_long
0    4.97      3495  36.0788  -81.1781  36.011293  -82.048315
1  107.23       149  48.8878 -118.2105  49.159047 -118.186462
2  220.11      4154  42.1808 -112.2620  43.150704 -112.154481
3   45.00      1939  46.2306 -112.1138  47.034331 -112.561071
4   41.96        99  38.4207  -79.4629  38.674999  -78.632459

In [20]:
df_scaling.isnull().sum()

amt           0
city_pop      0
lat           0
long          0
merch_lat     0
merch_long    0
dtype: int64

In [21]:
df_scaling = df_scaling.dropna()

df_scaling.head()

      amt  city_pop      lat      long  merch_lat  merch_long
0    4.97      3495  36.0788  -81.1781  36.011293  -82.048315
1  107.23       149  48.8878 -118.2105  49.159047 -118.186462
2  220.11      4154  42.1808 -112.2620  43.150704 -112.154481
3   45.00      1939  46.2306 -112.1138  47.034331 -112.561071
4   41.96        99  38.4207  -79.4629  38.674999  -78.632459

In [22]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

min_max_scaler = MinMaxScaler()

df_min_max = pd.DataFrame(
    min_max_scaler.fit_transform(df_scaling),
    columns=df_scaling.columns
)

print("Min-Max Scaled Data:")
print(df_min_max.head())

Min-Max Scaled Data:
        amt  city_pop       lat      long  merch_lat  merch_long
0  0.000137  0.001194  0.343968  0.864638   0.350302    0.848602
1  0.003670  0.000043  0.618450  0.485682   0.621488    0.486208
2  0.007569  0.001421  0.474727  0.546553   0.497559    0.546697
3  0.001520  0.000659  0.561509  0.548070   0.577663    0.542619
4  0.001415  0.000026  0.394153  0.882190   0.405244    0.882857

In [23]:
standard_scaler = StandardScaler()

df_standard = pd.DataFrame(
    standard_scaler.fit_transform(df_scaling),
    columns=df_scaling.columns
)

print("Standardized Data:")
print(df_standard.head())

Standardized Data:
        amt  city_pop       lat      long  merch_lat  merch_long
0 -0.407826 -0.282589 -0.484420  0.657620  -0.494354    0.593864
1  0.230039 -0.293670  2.039120 -2.033870   2.078699   -2.030341
2  0.934149 -0.280406  0.717754 -1.601537   0.902849   -1.592323
3 -0.158132 -0.287742  1.515617 -1.590766   1.662886   -1.621848
4 -0.177094 -0.293835 -0.023035  0.782279   0.026941    0.841909

In [24]:
robust_scaler = RobustScaler()

df_robust = pd.DataFrame(
    robust_scaler.fit_transform(df_scaling),
    columns=df_scaling.columns
)

print("Robust Scaled Data:")
print(df_robust.head())

Robust Scaled Data:
        amt  city_pop       lat      long  merch_lat  merch_long
0 -0.578990  0.053051 -0.447479  0.378534  -0.464366    0.323525
1  0.812491 -0.117794  1.302409 -1.846971   1.355748   -1.845569
2  2.348483  0.086699  0.386139 -1.489489   0.523981   -1.483516
3 -0.034290 -0.026398  0.939398 -1.480583   1.061612   -1.507921
4 -0.075657 -0.120347 -0.127543  0.481611  -0.095615    0.528552

In [25]:
print("Original Data:")
print(df_scaling.head())

Original Data:
      amt  city_pop      lat      long  merch_lat  merch_long
0    4.97      3495  36.0788  -81.1781  36.011293  -82.048315
1  107.23       149  48.8878 -118.2105  49.159047 -118.186462
2  220.11      4154  42.1808 -112.2620  43.150704 -112.154481
3   45.00      1939  46.2306 -112.1138  47.034331 -112.561071
4   41.96        99  38.4207  -79.4629  38.674999  -78.632459

In [26]:
print("Min-Max Scaled Data:")
print(df_min_max.head())

Min-Max Scaled Data:
        amt  city_pop       lat      long  merch_lat  merch_long
0  0.000137  0.001194  0.343968  0.864638   0.350302    0.848602
1  0.003670  0.000043  0.618450  0.485682   0.621488    0.486208
2  0.007569  0.001421  0.474727  0.546553   0.497559    0.546697
3  0.001520  0.000659  0.561509  0.548070   0.577663    0.542619
4  0.001415  0.000026  0.394153  0.882190   0.405244    0.882857

In [27]:
print("Standardized Data:")
print(df_standard.head())

Standardized Data:
        amt  city_pop       lat      long  merch_lat  merch_long
0 -0.407826 -0.282589 -0.484420  0.657620  -0.494354    0.593864
1  0.230039 -0.293670  2.039120 -2.033870   2.078699   -2.030341
2  0.934149 -0.280406  0.717754 -1.601537   0.902849   -1.592323
3 -0.158132 -0.287742  1.515617 -1.590766   1.662886   -1.621848
4 -0.177094 -0.293835 -0.023035  0.782279   0.026941    0.841909

In [28]:
print("Robust Scaled Data:")
print(df_robust.head())

Robust Scaled Data:
        amt  city_pop       lat      long  merch_lat  merch_long
0 -0.578990  0.053051 -0.447479  0.378534  -0.464366    0.323525
1  0.812491 -0.117794  1.302409 -1.846971   1.355748   -1.845569
2  2.348483  0.086699  0.386139 -1.489489   0.523981   -1.483516
3 -0.034290 -0.026398  0.939398 -1.480583   1.061612   -1.507921
4 -0.075657 -0.120347 -0.127543  0.481611  -0.095615    0.528552

In [29]:
# Exp. 5.3 - Outlier Detection

TotalTransaction = train_df["amt"]

TotalTransaction.head(10)

0      4.97
1    107.23
2    220.11
3     45.00
4     41.96
5     94.63
6     44.54
7     71.65
8      4.27
9    198.39
Name: amt, dtype: float64

In [30]:
TotalTransaction.describe()

count    1.296675e+06
mean     7.035104e+01
std      1.603160e+02
min      1.000000e+00
25%      9.650000e+00
50%      4.752000e+01
75%      8.314000e+01
max      2.894890e+04
Name: amt, dtype: float64

In [32]:
import numpy as np
import pandas as pd

In [33]:
TotalTransaction = train_df["amt"]

TotalTransaction[np.abs(TotalTransaction) > 1000]

232        1055.47
511        1636.87
723        1047.52
824        1433.54
1480       1025.38
            ...
1294390    1006.48
1294714    2090.14
1295108    1064.44
1295255    1063.03
1295491    1210.91
Name: amt, Length: 3936, dtype: float64

In [34]:
train_df[np.abs(TotalTransaction) > 1000]

             amt      lat      long  city_pop  merch_lat  merch_long  is_fraud
232      1055.47  40.7692 -103.0968       648  39.940564 -103.528231         0
511      1636.87  31.6489  -82.1982      1324  31.608415  -83.145823         0
723      1047.52  35.2087  -92.2123       969  34.887449  -92.623326         0
824      1433.54  45.6710 -121.8686      1288  45.873314 -121.589038         0
1480     1025.38  36.4715  -82.4834     87124  37.421987  -81.873400         0
...          ...      ...       ...       ...        ...         ...       ...
1294390  1006.48  42.5545  -90.3508      1306  41.585645  -90.692572         1
1294714  2090.14  40.8626  -91.9534       888  40.282456  -91.566151         0
1295108  1064.44  37.6858  -83.9862     13061  38.220812  -84.138702         1
1295255  1063.03  31.8599 -102.7413        23  30.971658 -102.494584         1
1295491  1210.91  27.6330  -80.4031    105638  28.216707  -79.855648         1

[3936 rows x 7 columns]

In [35]:
TotalTransaction[np.abs(TotalTransaction) > 5000]

12084       5444.24
17743      11872.21
25944       6337.25
37315      10776.59
42665       5234.79
             ...
1262258    10665.33
1270060    10881.08
1270196     6438.07
1277159     6202.65
1290513    12176.55
Name: amt, Length: 136, dtype: float64

In [36]:
train_df[np.abs(TotalTransaction) > 5000]

,amt,lat,long,city_pop,merch_lat,merch_long,is_fraud
12084,5444.24,42.2470,-73.7552,17867,41.588036,-73.799288,0
17743,11872.21,43.6849,-71.2551,1368,43.235621,-71.391741,0
25944,6337.25,29.9975,-90.2146,137067,30.442968,-89.442589,0
37315,10776.59,29.3641,-98.4924,1595797,29.772325,-98.593405,0
42665,5234.79,40.0235,-120.7986,128,40.817192,-120.227632,0
...,...,...,...,...,...,...,...
1262258,10665.33,41.0036,-78.1104,489,40.090804,-78.941345,0
1270060,10881.08,44.6087,-74.9732,69,45.300250,-75.881408,0
1270196,6438.07,43.9742,-71.1503,3807,43.801646,-70.720339,0
1277159,6202.65,36.7651,-94.0492,760,36.478149,-93.328732,0
1290513,12176.55,32.2779,-97.2351,5875,32.931738,-96.358340,0

In [37]:
outliers_1000 = train_df[
    np.abs(TotalTransaction) > 1000
]

print("Number of transactions above 1000:")
print(len(outliers_1000))

Number of transactions above 1000:
3936

In [38]:
outliers_5000 = train_df[
    np.abs(TotalTransaction) > 5000
]

print("Number of transactions above 5000:")
print(len(outliers_5000))

Number of transactions above 5000:
136

In [39]:
Q1 = train_df["amt"].quantile(0.25)
Q3 = train_df["amt"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

Q1: 9.65
Q3: 83.14
IQR: 73.49
Lower Bound: -100.58499999999998
Upper Bound: 193.375

In [40]:
iqr_outliers = train_df[
    (train_df["amt"] < lower_bound) |
    (train_df["amt"] > upper_bound)
]

iqr_outliers.head(10)

       amt      lat      long  city_pop  merch_lat  merch_long  is_fraud
2   220.11  42.1808 -112.2620      4154  43.150704 -112.154481         0
9   198.39  36.5220  -87.3490    151785  37.179198  -87.485381         0
16  327.00  36.3850  -98.0727      1078  36.384092  -99.048472         0
17  341.67  38.9763  -87.3667      4081  38.674491  -88.305767         0
36  207.36  40.6729  -73.5365     34496  40.202538  -73.859212         0
39  221.81  40.8095  -72.8229      3285  40.011959  -72.594808         0
43  212.75  37.9931 -100.9893      2691  38.862183 -101.234087         0
54  212.45  30.8985  -87.1332      5719  31.414174  -87.138632         0
67  303.47  36.7558  -83.1838       581  36.394203  -82.514283         0
73  317.14  35.2563 -111.9500       759  35.268124 -112.682895         0

In [41]:
print("Number of IQR Outliers:")
print(len(iqr_outliers))

Number of IQR Outliers:
67290

In [42]:
iqr_outliers["is_fraud"].value_counts()

is_fraud
0    61585
1     5705
Name: count, dtype: int64

In [43]:
train_df["is_fraud"].value_counts()

is_fraud
0    1289169
1       7506
Name: count, dtype: int64

In [44]:
train_df.groupby("is_fraud")["amt"].describe()

,count,mean,std,min,25%,50%,75%,max
is_fraud,,,,,,,,
0,1289169.0,67.667110,154.007971,1.00,9.6100,47.280,82.540,28948.90
1,7506.0,531.320092,390.560070,1.06,245.6625,396.505,900.875,1376.04

In [45]:

print("OUTLIER DETECTION")

print("\nTotal Transactions:")
print(len(train_df))

print("\nTransactions Above 1000:")
print(len(outliers_1000))

print("\nTransactions Above 5000:")
print(len(outliers_5000))

print("\nIQR Outliers:")
print(len(iqr_outliers))

print("\nFraud Distribution Among IQR Outliers:")
print(iqr_outliers["is_fraud"].value_counts())

OUTLIER DETECTION

Total Transactions:
1296675

Transactions Above 1000:
3936

Transactions Above 5000:
136

IQR Outliers:
67290

Fraud Distribution Among IQR Outliers:
is_fraud
0    61585
1     5705
Name: count, dtype: int64